### ISSUE TITLE
@tus/s3-store: Doesn't work with R2

### ISSUE THREAD

**Issue by push1st1k** [tus/tus-node-server#551] opened 2024-01-12 13:35 UTC
After upgrading to the 1.2.0 version it's not possible to upload files to R2 anymore due to added 'Tagging' header.
The error message is: `The header 'x-amz-tagging' is not supported by R2` (it's really not supported by R2 https://developers.cloudflare.com/r2/api/s3/api/).

[This PR](https://github.com/tus/tus-node-server/pull/513) introduced that new 'Tagging' header.

It would be great to detect which provider (S3 or R2) is used or add an option to configure that.

**Comment by Murderlon** [comment] 2024-01-15 09:44
Thanks for the issue. We'll take a look.

Duplicate of https://github.com/tus/tus-node-server/issues/538

**Closed by Murderlon** 2024-01-15 09:44 UTC
