### ISSUE TITLE
Upload not finalized on S3

### ISSUE THREAD

**Issue by JanKups** [tus/tus-node-server#462] opened 2023-07-27 14:21 UTC
I've setup the following for @tus/server together with @tus/s3-store:

```
const {Server} = require('@tus/server')
const {S3Store} = require('@tus/s3-store')

const s3Store = new S3Store({
  partSize: 8 * 1024 * 1024, // Each uploaded part will have ~8MB,
  s3ClientConfig: {
    bucket: process.env.AWS_BUCKET,
    region: process.env.AWS_REGION,
    credentials: {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    },
  },
})
const server = new Server({path: '/uploads', datastore: s3Store})

const uploadApp = express();
uploadApp.all("*", tusServer.handle.bind(tusServer));

app.use(
  "/uploads",
  passport.authenticate("jwt", { session: false }),
  uploadApp
);
```

I'm using tus-js-client on the frontend, setup as in the [example](https://github.com/tus/tus-js-client#example).

When uploading to S3 the file is successfully send and the browser received the "onSuccess" message. However the files are placed in S3 as follows:

![CleanShot 2023-07-27 at 16 02 18](https://github.com/tus/tus-node-server/assets/7448338/45d868af-6541-4537-a6ea-1a974f5d039d)

It looks as if the upload is not finalized (from what I know about multiuploads with _CompleteMultipartUploadCommand_). Am I missing something, or can the passport auth cause an issue?

**Comment by Murderlon** [comment] 2023-07-27 14:26
Likely a duplicate of #415. Taking a look next week.

**Closed** 2023-08-24 12:56 UTC
Labels: duplicate
