### ISSUE TITLE
Stateless behavior in a replicated tus cluster (k8s)

### ISSUE THREAD

**Issue by pbell23** [tus/tus-node-server#428] opened 2023-05-11 12:12 UTC
I could not figure out wether tus is designed to be stateless or stateful. Some comments on issues state that it's stateless but some other say that it's not.

In my particular case, I'm building a tus cluster on kubernetes with multiple replicated tus instances. When uploading a file, by default, all requests are not guaranteed to be served by the same tus instance (pod in k8s). This leads to some errors (PATCH and HEAD requests return a 404 for the file id while it exist in the persistent volume which is shared accross instances). If I enable sticky session on the reverse proxy I use (traefik), everything works well as one upload will be handled by one unique tus instance.

Is this a normal behaviour ? Is tus stateful and needs some session/memory data from the same tus instance on each requests for one upload ?

**Comment by Murderlon** [comment] 2023-05-11 12:20
Duplicate of #408

But we can continue the discussion.

**Closed by Murderlon** 2023-05-11 12:20 UTC
Labels: duplicate
