### ISSUE TITLE
Extract out each DataStore to separate npm modules

### ISSUE THREAD

**Issue by bhstahl** [tus/tus-node-server#69] opened 2017-03-13 11:55 UTC
Users should be able to choose their appropriate DataStore, and not deal with all stores. Right now all stores are included in this module, which causes issues such as #56 and #54.

This will serve as a progress issue, leading to the closing of #61.

- [ ] [tus-datastore-abstract](https://www.npmjs.com/package/tus-datastore-abstract)
- [ ] [tus-datastore-filesystem](https://www.npmjs.com/package/tus-datastore-filesystem)
- [ ] [tus-datastore-gcs](https://www.npmjs.com/package/tus-datastore-gcs)

**Comment by kvz** [comment] 2017-07-11 11:29
FWIF, for uppy.io we're considering https://lernajs.io/, so that we get to keep all code in one repo, but push out separate npm modules. advantages:

- easy to change structure across all modules while the project is still young, and propose those as a single pr/atomic unit
- one issue tracker
- share ci/testing boilerplate, build tools, etc without the need for duplication or (leaky) abstraction

**Comment by tkrugg** [comment] 2018-08-18 16:16
looks like a dup for https://github.com/tus/tus-node-server/issues/61

**Comment by Murderlon** [comment] 2022-09-01 13:46
Closing indeed as a duplicate of #61

**Closed by Murderlon** 2022-09-01 13:46 UTC
