### ISSUE TITLE
Mixed content error - Page load over https buyt requested url is insecure

### ISSUE THREAD

**Issue by D2rTech** [tus/tus-node-server#550] opened 2024-01-09 14:16 UTC
We keep on getting this error and seems to be a problem at tus level... any fixes?
Mixed Content: The page at 'https://www.xxx.com/library' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxx/files/files/8d3a8f949a57cb297980231dc6b58497'. This request has been blocked; the content must be served over HTTPS.

domain masked

**Comment by Murderlon** [comment] 2024-01-09 14:19
Duplicate of https://github.com/tus/tus-node-server/issues/469

**Closed by Murderlon** 2024-01-09 14:19 UTC
Labels: duplicate
