### ISSUE TITLE
Custom configstore file path

### ISSUE THREAD

**Issue by vanilla38** [tus/tus-node-server#54] opened 2016-09-26 11:19 UTC
Hello, I dont really know how to get more infos about tus FileStore object options so I ask here, is there a way to set a custom location and name for the configstore file ? 
Thank yo uby advance and sorry for using this issue tracker to do that. 

Have a great day ;)

**Comment by bhstahl** [comment] 2016-09-26 21:57
Hey @vanilla38, take a look at [Custom File Names](https://github.com/tus/tus-node-server#custom-file-names) in the Readme. You just need to write a function that returns the file names and pass it in for the `namingFunction` property of the `DataStore` constructor. Let me know if you have any trouble.

**Comment by vanilla38** [comment] 2016-09-26 22:50
Hey, thanks for the quick answer, you probably misunderstood my question, what I ask for is a way to set a custom Configstore db json file location, I mean the json DB file. Thanks.

**Comment by bhstahl** [comment] 2016-09-27 14:43
Whoops, sorry I misread @vanilla38 . According to the [`configstore`](https://www.npmjs.com/package/configstore) package we can [set a path](https://www.npmjs.com/package/configstore#globalconfigpath) in the constructor. We'll just need to add handling of a  [FileStore](https://github.com/tus/tus-node-server/blob/5943566baaadb7db3cdd8a37a3c6984ea82066ca/lib/stores/FileStore.js#L29) options parameter to pass through to the constructor of Configstore. Feel free to open a PR if you need this immediately!

**Comment by Acconut** [comment] 2018-05-01 07:31
You should be able to change the configuration directory using the `XDG_CONFIG_HOME` environment variable (we are using [configstore](https://github.com/yeoman/configstore/blob/master/readme.md) internally which can be configured in that way).

Besides that I am closing this as a duplicate of https://github.com/tus/tus-node-server/issues/62.

**Closed by Acconut** 2018-05-01 07:31 UTC
