### ISSUE TITLE
EACCES: permission denied, open '/tmp/.config/configstore/tus-node-server-0.2.10.json.276941652' You don't have access to this file.

### ISSUE THREAD

**Issue by keremkusmezer** [tus/tus-node-server#102] opened 2018-03-30 00:09 UTC
EACCES: permission denied, open '/tmp/.config/configstore/tus-node-server-0.2.10.json.276941652'
You don't have access to this file. 

Exception with Node.js 8.9.3 on AWS Instance when trying to deploy the server.
It occurs randomly, it there a way to target configstore to somewhere else

**Comment by Acconut** [comment] 2018-05-01 07:28
You should be able to change the configuration directory using the `XDG_CONFIG_HOME` environment variable (we are using [configstore](https://github.com/yeoman/configstore/blob/master/readme.md) internally which can be configured in that way).

Besides that I am closing this as a duplicate of https://github.com/tus/tus-node-server/issues/62.

**Closed by Acconut** 2018-05-01 07:28 UTC
