### ISSUE TITLE
Request for Next.js App Router Support and Example Usage

### ISSUE THREAD

**Issue by CarlosZiegler** [tus/tus-node-server#657] opened 2024-09-23 20:43 UTC
### Initial checklist

- [X] I understand this is a feature request and questions should be posted in the [Community Forum](https://community.transloadit.com/c/tus/6)
- [X] I searched [issues](https://github.com/tus/tus-node-server/issues?q=is%3Aissue) and couldn’t find anything (or linked relevant results below)

### Problem

Hi TUS team,

I’m currently integrating TUS into a project that uses the Next.js App Router (with /app directory structure). However, I’ve noticed that the examples and documentation primarily focus on the older Next.js page-based router.

Could you confirm whether there’s official support for the Next.js App Router? If so, I’d appreciate any examples or best practices that could help in implementing bus with this new router structure. If this feature is not yet supported, do you have any insights on when it might be available?

Thanks in advance!

### Solution

This will be works on APP router like pages/api

### Alternatives

I dont know :)

**Comment by Murderlon** [comment] 2024-09-24 07:45
Tus is just a barebones Node.js HTTP handler so it can be integrated everywhere and into everything. It shouldn't be too hard to add it to the app router, you probably have to export the same handler a couple times as you know have to export per HTTP method. 

I will take a look at it but if you're already experimenting yourself would be great to update here on your progress.

**Comment by Murderlon** [comment] 2024-12-02 08:37
Turns out this is not possible right now without some significant work on @tus/server, which is the same work that would need to happen for #461

**Comment by Murderlon** [comment] 2024-12-23 10:04
Closing as duplicate of #461

**Closed by Murderlon** 2024-12-23 10:04 UTC
